version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  initdb:
    image: postgres:14-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/run.sh:/docker-entrypoint-initdb.d/run.sh
    command: ["sh", "/docker-entrypoint-initdb.d/run.sh"]
    env_file:
      - .env
    depends_on:
      - postgres
