FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY ../ .

# Expose the port on which your application will run
EXPOSE 3000

# Start the application
CMD ["npm", "start"]